#!/bin/bash
## Semi-automatic script to
## download build and install
## ffmpeg-full on arch linux
## Req.: grep hash head tail wc git wget make gcc...
## Use: ./get_ffmpeg-full_arch
## Author Andrew S. Licence MIT
## https://github.com/quarkscript/Build_from_source

## get required Simple_func_scripts
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/adnlalwp
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/cxx_flags
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/mcolif
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/mpbsmpks
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/edfpb
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/rmdtpi
chmod +x adnlalwp cxx_flags mcolif mpbsmpks rmdtpi edfpb
./cxx_flags

## For make a local hardware independent builds uncomment next line
#echo "">cxxflags.txt

mkdir aur_depends
cp adnlalwp cxx_flags mcolif mpbsmpks cxxflags.txt rmdtpi edfpb aur_depends
cp aur_depends ffmpeg -r
cd aur_depends
 aur_ffdep=('
             https://aur.archlinux.org/rockchip-mpp.git
             https://aur.archlinux.org/libmysofa.git
             https://aur.archlinux.org/xavs.git
             https://aur.archlinux.org/vo-amrwbenc.git
             https://aur.archlinux.org/shine.git
             https://aur.archlinux.org/sndio.git
             https://aur.archlinux.org/libopenmpt-svn.git
             https://aur.archlinux.org/openh264.git
             https://aur.archlinux.org/kvazaar.git
             https://aur.archlinux.org/libilbc.git
             https://aur.archlinux.org/flite1-patched.git
             https://aur.archlinux.org/libbs2b.git
             https://aur.archlinux.org/chromaprint-fftw.git
             https://aur.archlinux.org/blackmagic-decklink-sdk.git
             https://aur.archlinux.org/libmfx.git
             https://aur.archlinux.org/vmaf.git
             https://aur.archlinux.org/intel-media-driver.git
             https://aur.archlinux.org/intel-media-sdk.git
             https://aur.archlinux.org/codec2.git
             https://aur.archlinux.org/ndi-sdk.git')
for i in $(echo $aur_ffdep )
    do
    git clone $i
done
echo "">deps1
echo "">deps2
for i in $(ls -d */ | sed -e 's/\///g')
    do
    ./edfpb "$i/PKGBUILD"
    cat deps2 >>deps1
    cat deps1 >>aur_dep_list
done

## get aur req packs
./rmdtpi "aur_dep_list"
 req_pack_list=$(cat aur_dep_list.req | sed 's/intel-media-driver//g')
if [ "$req_pack_list" != "" ]
    then
        echo !!!
        echo build aur depends of ffmpeg-full require absent packages:
        echo $req_pack_list
        echo !!! super-user password is required to install it
        sudo pacman -S $req_pack_list
fi

##firstly make and install intel-media-driver
mkdir 1
cp -r intel-media-driver 1/
cp adnlalwp cxx_flags mcolif mpbsmpks cxxflags.txt rmdtpi edfpb 1/
rm -rf intel-media-driver
cd 1
./mpbsmpks -u
if [ -e *pkg.tar.xz ]; then
    echo !!! 
    echo super-user password is required to install intel-media-driver
    sudo pacman -U *pkg.tar.xz
fi
cd ..
cp -r 1 ../inteldriver
rm -fr 1

## due to PKGBUILD can be written in non unique way, some mods of some PKGBUILDs need to be applied manual...
./mcolif 'libilbc/PKGBUILD' 'make' 'make' "make -j$(($(grep 'model name' /proc/cpuinfo --count)+1))"
./mcolif 'libopenmpt-svn/PKGBUILD' 'make ' 'make ' "make -j$(($(grep 'model name' /proc/cpuinfo --count)+1)) "
## make and install other req. aur packages
./mpbsmpks -u
if [ -e *pkg.tar.xz ]; then
    echo !!!
    echo super-user password is required to install aur depends of ffmpeg-full
    sudo pacman -U *pkg.tar.xz
fi

cd ../ffmpeg
git clone https://aur.archlinux.org/ffmpeg-full.git
echo "">deps1
echo "">deps2
./edfpb "ffmpeg-full/PKGBUILD"
cat deps2 >>deps1
cat deps1 >>ffmpeg_full_req
./edfpb "ffmpeg-full/PKGBUILD" "depends_x86_64=('"
cat deps2 >>deps1
cat deps1 >>ffmpeg_full_req
./edfpb "ffmpeg-full/PKGBUILD" "makedepends_x86_64="
cat deps2 >>deps1
cat deps1 >>ffmpeg_full_req
# ## for intel qsv....
# ./edfpb "ffmpeg-full/PKGBUILD" "optdepends_x86_64="
# cat deps2 >>deps1
# cat deps1 >>ffmpeg_full_req
./rmdtpi "ffmpeg_full_req"
req_pack_list_ffmpeg=$(cat ffmpeg_full_req.req)
if [ "$req_pack_list_ffmpeg" != "" ]
    then
        echo !!!
        echo build ffmpeg-full require absent packages:
        echo $req_pack_list_ffmpeg
        echo !!!
        echo due to reorganize arch repo and not synced ffmpeg-full 
        echo dependencies with it, some of packages may reinstall
        echo !!!
        echo super-user password is required to install it
        sudo pacman -S $req_pack_list_ffmpeg
fi
## switch to chromaprint if chromaprint-fftw isn't option
if  $(pacman -Qqe | grep -xq chromaprint); then
    ./mcolif 'ffmpeg-full/PKGBUILD' 'chromaprint-fftw' 'chromaprint-fftw' 'chromaprint'
fi
## make and install ffmpeg-full
extrafl='--extra-cxxflags=" '
extrafl+=$(cat cxxflags.txt)
extrafl+=' " \'
cd ffmpeg-full
../adnlalwp 'PKGBUILD' 'prefix=' "$extrafl" 
 cd ..
./mpbsmpks
echo !!!
echo super-user password is required for install ffmpeg-full
sudo pacman -U *pkg.tar.xz

## as intelmedia propose
if ( $(lspci | grep VGA | grep Intel -q) ); then
    cat /etc/profile.d/intel-media.sh | sed -e 's/#export LIBVA_DRIVER_NAME=iHD/export LIBVA_DRIVER_NAME=iHD/g'>intel-media.sh
    sudo mv -f intel-media.sh /etc/profile.d/intel-media.sh
fi
