#!/bin/bash
## Semi-automatic script to
## download build and install
## vlc-git on arch linux
## Req.: grep hash head tail wc git wget make gcc...
## Use: ./get_last_vlc_arch
## Author Andrew S. License MIT
## https://github.com/quarkscript/Build_from_source

## get required Simple_func_scripts
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/adnlalwp
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/cxx_flags
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/mcolif
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/mpbsmpks
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/edfpb
wget https://github.com/quarkscript/Simple_func_scripts/raw/master/rmdtpi
chmod +x adnlalwp cxx_flags mcolif mpbsmpks rmdtpi edfpb
./cxx_flags

## For make a local hardware independent build uncomment next line
#echo "">cxxflags.txt

mkdir aurdep
for f in adnlalwp cxx_flags mcolif mpbsmpks rmdtpi edfpb cxxflags.txt; do
    cp $f aurdep/$f
done
cd aurdep
git clone https://aur.archlinux.org/aribb24.git
./mpbsmpks -u
if [ -e *pkg.tar.xz ]; then
    echo !!! sudo password is required to install vlc aur-deps
    sudo pacman -U *pkg.tar.xz
fi
cd ..
git clone https://aur.archlinux.org/vlc-git.git
mv -f aurdep vlc-git/aurdep
## mod deps if ffmpeg-full installed
if  $(pacman -Qqe | grep -xq ffmpeg-full); then
    ./mcolif 'vlc-git/PKGBUILD' 'ffmpeg' 'ffmpeg' 'ffmpeg-full'
fi
if  $(pacman -Qqe | grep -xq chromaprint-fftw); then
    ./mcolif 'vlc-git/PKGBUILD' 'chromaprint' 'chromaprint' 'chromaprint-fftw'
fi
## experimental mods
./mcolif 'vlc-git/PKGBUILD' 'kdelibs' 'kdelibs' 'kdelibs4support'
./adnlalwp "vlc-git/PKGBUILD" "hostname -f" "  sed 's|kde4-config|kf5-config|g' -i configure.ac"
./adnlalwp "vlc-git/PKGBUILD" "hostname -f" "  sed 's|kde4-config|kf5-config|g' -i configure"
## extract deps
./edfpb "vlc-git/PKGBUILD"
cat deps2 >>deps1
./rmdtpi "deps1"
req_pacs_list=$(cat deps1.req)
## cheks for absent deps
if [ "$req_pacs_list" != "" ]
    then
        echo "
building vlc required absent packages:
$req_pacs_list
due to continiously reorganaze arch-repo, some packages
may reinstall
!!! sudo password is required to install it"
        sudo pacman -S $req_pacs_list
fi
## fix PKGBUILD 22.06.2018
./adnlalwp 'vlc-git/PKGBUILD' 'export RCC' '  export LIBS="-lxkbcommon"'
## make vlc
./mpbsmpks
echo !!! sudo password is required to install vlc
sudo pacman -U *pkg.tar.xz
